### ISSUE TITLE
Input file type and output file process

### ISSUE THREAD

**Issue by zhiyi1988** [SvenBaileyLab/HisTrader#1]
Hi, thank you for developing this useful program. I have used it to detect NFRs from H3K27Ac ChIP-seq. The results looks good, but I just want to make sure that I have used the program correctly. 

I actually did not use "--broad" option in MACS3, which means peaks I called are not broad (i.e. not the *.broadPeak file). However, I still have NFRs in the H3K27Ac peaks I detected. So it is actually OK to use *.narrowPeak results when detecting NFRs from H3K27Ac peaks?

Another question is that if I have multiple NFR results from different biological replicates, is there a quick way to get consensus NFRs?

Thank you for your time, regards!

**Comment by SvenBaileyLab** [comment]
Hi, 

It would depend on the question, using the .narrowPeak file should be okay, but you may miss NFRs if the nucleosomes are called separately. I would suggest viewing the results in a browser.

For finding consensus NFRs you could use bedtools intersect or a similar tool on the called NFRs. I hope that helps.

Best regards.
